package com.softserve.itacademy.model;

public enum Genre {
    REALISM, IMPRESSIONISM, EXPRESSIONISM, ABSTRACT, SURREALISM, LANDSCAPE,
    STILL_LIFE, HISTORICAL, GENRE, PORTRAIT, MINIMALIST, OP_ART, POP_ART, POINTILLIST,
    FAUVIST, CUBIST, SYMBOLIST, ART_NOUVEAU, ART_DECO, BAROQUE, ROCOCO, ROMANTIC, RENAISSANCE,
    MANNERIST, GOTHIC, BYZANTINE, FOLK, NAIVE, OUTSIDER

}
